### ISSUE TITLE
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:

### ISSUE THREAD

**Issue by abysw** [hsigeman/findZX#17]
Hey hsigeman,
I could run the pipeline successfully before the New Year, but now, I'm encountering errors when trying to run the same task, and it fails quickly. I can not download the data directly using wget after this holidaies, must add "--no-check-certificate." This might be the reason for the errors. Could you help me?
###############################################################################
[Tue Jan 16 14:10:48 2024]
Error in rule trim_reads_pe:
    jobid: 0
    output: results/Batch10/trimmed/P28020_258__homogametic.1.fastq.gz, results/Batch10/trimmed/P28020_258__homogametic.2.fastq.gz, results/Batch10/trimmed/P28020_258__homogametic.1.unpaired.fastq.gz, results/Batch10/trimmed/P28020_258__homogametic.2.unpaired.fastq.gz
    log: results/Batch10/logs/trimmomatic/P28020_258__homogametic.log (check log file(s) for error message)
    conda-env: */01.findZX/findZX/.snakemake/conda/b0e7337125a0f80d5a981ed4a184466a

RuleException:
URLError in line 21 of */yuan/01.findZX/findZX/workflow/rules/trimming.smk:
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
  File "*/miniconda3/envs/findzx/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2349, in run_wrapper
  File "/*/01.findZX/findZX/workflow/rules/trimming.smk", line 21, in __rule_trim_reads_pe
  File "/*miniconda3/envs/findzx/lib/python3.9/urllib/request.py", line 214, in urlopen
  File "/*miniconda3/envs/findzx/lib/python3.9/urllib/request.py", line 517, in open
  File "/*/miniconda3/envs/findzx/lib/python3.9/urllib/request.py", line 534, in _open
  File "/*/miniconda3/envs/findzx/lib/python3.9/urllib/request.py", line 494, in _call_chain
.......
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by hsigeman** [comment]
Hi, 

Sorry to hear that you are having problems running the pipeline, but since this looks like a certificate issue and you are also having problems with wget I'm not sure what to suggest. 

The solution will depend on your operating system so the easiest way might be to just google the error message (`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate`). 

Some people seem to have solved it using this command but it might not work for you: 
`pip3 install --upgrade certifi`

Good luck, hope you figure it out!
Hanna

**Comment by abysw** [comment]
Hey Hanna,

**Comment by abysw** [comment]
Hey Hanna,

Unfortunately, it is not working for me, even though the pipeline worked before. I may need to seek assistance from IT support.

$pip3 install --upgrade certifi
Requirement already satisfied: certifi in /crex/proj/snic2020-2-25/nobackup/yuan/miniconda3/envs/findZX/lib/python3.9/site-packages (2023.11.17)
Thank you.
Yuan

**Comment by abysw** [comment]
Hey hanna,

I re-download the pipeline, and reinstall the certifi after uninstalled, it seems work now.

Thank you.
Yuan
