### ISSUE TITLE
get the contig name from results

### ISSUE THREAD

**Issue by Sanrrone** [hsigeman/findZX#3]
Dears,
Along with greeting you, I was wondering if there is a way to recover the name of the contig that the software tag as Homogametic. For example, the resulting pdf shows charts with the coverage of most important contigs. but the names appear truncated. is there a way to get the name? what file should I check?

thanks in advance.

**Comment by hsigeman** [comment]
Hi!

At this stage, the pipeline does not generate a list of homogametic contigs/scaffolds/chromosomes automatically. The reason for this is that it would be difficult to set thresholds that works for all types of sex chromosome systems. Instead, we recommend users to inspect the output plots manually to identify candidate homogametic contigs/scaffolds/chromosomes, which can then be found through the provided output data tables.

Specifically, the last page of each output figure (multi-page PDF format) contain links to the data tables used to create each figure. Using this data, you should be able to connect outlier data points with the correct contig ID. There is also a README file provided in the output table directory, where you can read about the contents of each column. 

Long contig names will sometimes lead to suboptimal plots, unfortunately. Plot type 1 (plots starting with "1_") is provided in two different versions for precicely this reason, one with horizontal X-axis labels and one with vertical X-axis labels. However, there may be other plot types where long contig names may be truncated and the data tables should hopefully help with these issues. 

Hope this helps! 
Hanna
