### ISSUE TITLE
ERROR IN Job 26: Calculates mean heterozygosity per sex and 5kb window

### ISSUE THREAD

**Issue by zhuangfjnu** [hsigeman/findZX#4]
Hi ,
I encounter a error message in job26, the following is the report. Could you help me to solve it?
-------------------------
Job 26: Calculates mean heterozygosity per sex and 5kb window

Activating conda environment: /share/workplace/HIC/Software/findZX/.snakemake/conda/b083848ef9e9c8e2bab236b9bb0f6d16
/usr/bin/bash: line 1: workflow/scripts/sum_heterozygosity_per_5kb.sh: Permission denied
[Tue Jan 11 08:12:48 2022]
Error in rule proportion_heterozygosity_window_2:
    jobid: 26
    output: results/wa_female/variant_calling/wa.build.chr.heterozygosity.5kb.windows.NR.bed, results/wa_female/variant_calling/wa.build.chr.heterozygosity.sexAverage.NR.bed
    conda-env: /share/workplace/HIC/Software/findZX/.snakemake/conda/b083848ef9e9c8e2bab236b9bb0f6d16
    shell:
        
        workflow/scripts/sum_heterozygosity_per_5kb.sh results/wa_female/variant_calling/wa.build.chr.heterozygosity.5kb.windows.bed > results/wa_female/variant_calling/wa.build.chr.heterozygosity.5kb.windows.NR.bed
	    
        python3 workflow/scripts/mean_heterozygosity_per_sex.py results/wa_female/variant_calling/wa.build.chr.heterozygosity.5kb.windows.NR.bed no-synteny het:369__heterogametic homo:jxw23__homogametic > results/wa_female/variant_calling/wa.build.chr.heterozygosity.sexAverage.NR.bed
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job proportion_heterozygosity_window_2 since they might be corrupted:
results/wa_female/variant_calling/wa.build.chr.heterozygosity.5kb.windows.NR.bed
Job failed, going on with independent jobs.

**Comment by zhuangfjnu** [comment]
chmod +x sum_heterozygosity_per_5kb.sh
Solve this error.

**Comment by hsigeman** [comment]
Hi, 

Thanks a lot for bringing this issue (and the solution!) to my attention. I have now updated the file permissions for all bash scripts in Git (git update-index --chmod=+x), so that they should be set automatically when downloading findZX. 

Hanna
