### ISSUE TITLE
Issue with jobid: 27

### ISSUE THREAD

**Issue by quin2b** [hsigeman/findZX#9]
![Screenshot 2022-10-27 133540](https://user-images.githubusercontent.com/116682846/198370359-5e7fdc2c-81c9-4e91-92d6-7e680372a387.jpg)

I am still relatively new to using bioinformatics tools, so this may be a very simple solution that I am missing, so I would like to initially apologize. I've been stuck on this for a couple days now and I feel I've exhausted a lot of different avenues when trying to solve whatever issue is stopping me from running the analyses. 

I am still trying to run a practice analysis on the howler monkey reference genome, however when trying to use the provided code I get an error message in return.

If you know what I may be doing wrong, or something that I have missed please let me know as I am approaching my wits end with this. Again, I would like to thank you for your time and help!

**Comment by hsigeman** [comment]
Hi quin2b!

Thanks for bringing this to my attention and sorry to hear that you are having issues getting the pipeline to work.

Unfortunately, I have not been able to reproduce this error message on either of my platforms (Ubuntu and OSX), so it would be helpful to have some additional information from you.

Please attach the log file for the failed job (results/howler_monkey_test_dataset/logs/picard/dedup/subset_SRR9655171__heterogametic.log), and also the complete log file, and I will look into it as soon as I can.

Hanna

**Comment by hsigeman** [comment]
Closing this now. Let me know if you still need help!
